/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsni.view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import zavrsni.util.Alati;

/**
 *
 * @author Denis
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        lblNaslov.setText(Alati.NAZIV_APP + " | IZBORNIK");
        lblOperater.setText(Alati.getOperater());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProizvodi = new javax.swing.JButton();
        btnDjelatnici = new javax.swing.JButton();
        btnKupci = new javax.swing.JButton();
        btnRacuni = new javax.swing.JButton();
        btnOnama = new javax.swing.JButton();
        btnIzlaz = new javax.swing.JButton();
        lblNaslov = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        lblOperater = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProizvodi.setText("Proizvodi");
        btnProizvodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProizvodiActionPerformed(evt);
            }
        });

        btnDjelatnici.setText("Djelatnici");
        btnDjelatnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDjelatniciActionPerformed(evt);
            }
        });

        btnKupci.setText("Kupci");
        btnKupci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupciActionPerformed(evt);
            }
        });

        btnRacuni.setText("Računi");
        btnRacuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacuniActionPerformed(evt);
            }
        });

        btnOnama.setText("O nama");
        btnOnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnamaActionPerformed(evt);
            }
        });

        btnIzlaz.setText("Izlaz");
        btnIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzlazActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.add(lblOperater);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIzlaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDjelatnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProizvodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKupci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRacuni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov)
                .addGap(18, 18, 18)
                .addComponent(btnProizvodi)
                .addGap(18, 18, 18)
                .addComponent(btnDjelatnici)
                .addGap(18, 18, 18)
                .addComponent(btnKupci)
                .addGap(18, 18, 18)
                .addComponent(btnRacuni)
                .addGap(18, 18, 18)
                .addComponent(btnOnama)
                .addGap(18, 18, 18)
                .addComponent(btnIzlaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProizvodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProizvodiActionPerformed
        new ProzorProizvod().setVisible(true);
    }//GEN-LAST:event_btnProizvodiActionPerformed

    private void btnDjelatniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDjelatniciActionPerformed
        new ProzorDjelatnik().setVisible(true);
    }//GEN-LAST:event_btnDjelatniciActionPerformed

    private void btnKupciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupciActionPerformed
        new ProzorKupac().setVisible(true);
    }//GEN-LAST:event_btnKupciActionPerformed

    private void btnRacuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacuniActionPerformed
        new ProzorRacun().setVisible(true);
    }//GEN-LAST:event_btnRacuniActionPerformed

    private void btnOnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnamaActionPerformed
        Image slika = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        ImageIcon icon = new ImageIcon(slika);

        JOptionPane.showMessageDialog(getRootPane(),
                "Ovaj projekt nastao je tijekom pohađanja u Edunovi 2023. godine\n"
                + "Autor je Denis Simov",
                "Aplikacija Moto Trgovina", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_btnOnamaActionPerformed

    private void btnIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlazActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzlazActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDjelatnici;
    private javax.swing.JButton btnIzlaz;
    private javax.swing.JButton btnKupci;
    private javax.swing.JButton btnOnama;
    private javax.swing.JButton btnProizvodi;
    private javax.swing.JButton btnRacuni;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblOperater;
    // End of variables declaration//GEN-END:variables
}
